global:
  scrape_interval: 1s

scrape_configs:

  - job_name: "tester-110"
    static_configs:
      - targets:
          - "172.20.0.22:28015"

  - job_name: "tester-111"
    static_configs:
      - targets:
          - "172.20.0.29:28015"

  - job_name: "tester-112"
    static_configs:
      - targets:
          - "[fd00:f00d:cafe::7f00:15]:28015"